ElectroThunder/ElectroThunder/Controllers/ElectroThunderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectroThunder.Controllers
{
    public class ElectroThunderController : Controller
    {
        public ActionResult AlterarProdutos()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CadastrarProduto(Modelos.ProdutoModel p)
        {
            Business.ProdutoBusiness business = new Business.ProdutoBusiness();
            business.Inserir(p);
            return View();
        }
        public ActionResult CadastrarProduto()
        {
            return View();
        }
        public ActionResult ConsultarProduto()
        {
            Business.ProdutoBusiness business = new Business.ProdutoBusiness();
            return View(business.Consultar());
        }
        public ActionResult Contatos()
        {
            return View();
        }
        public ActionResult QuemSomos()
        {
            return View();
        }
        public ActionResult Inicio()
        {
            return View();
        }
        public ActionResult DeletarProduto(int ID,Modelos.ProdutoModel model)
        {
            Business.ProdutoBusiness business = new Business.ProdutoBusiness();
            Modelos.ProdutoModel produtoModel1 = business.Buscarid(ID);

            return View(model);
        }
        [HttpPost]
        public ActionResult DeletarPruduto(int id)
        {
            Business.ProdutoBusiness business = new Business.ProdutoBusiness();
            business.Deletarpro(id);

            return RedirectToAction("Consultar");
        }
        public ActionResult Alterar()
        {
            return View();
        }
        public ActionResult Alterar(int id)
        {
            Business.ProdutoBusiness business = new Business.ProdutoBusiness();
            Modelos.ProdutoModel p = new Modelos.ProdutoModel();

            return View(p);
        }

    }
}

ElectroThunder/ElectroThunder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectroThunder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ElectroThunder/ElectroThunder/Views/ElectroThunder/AlterarProduto.cshtml
@model ElectroThunder.Modelos.ProdutoModel

@{
    ViewBag.Title = "AlterarProduto";
}

<h2>AlterarProduto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProdutoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ElectroThunder/ElectroThunder/Views/ElectroThunder/AlterarProdutos.cshtml
@model ElectroThunder.Modelos.ProdutoModel

@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProdutoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volta para consulta", "ConsultarProduto")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectroThunder/ElectroThunder/Views/ElectroThunder/CadastrarProduto.cshtml
@model ElectroThunder.Modelos.ProdutoModel

@{
    ViewBag.Title = "CadastrarProduto";
}

<h2>CadastrarProduto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProdutoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ConsultarProduto")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectroThunder/ElectroThunder/Views/ElectroThunder/ConsultarProduto.cshtml
@model IEnumerable<ElectroThunder.Modelos.ProdutoModel>

@{
    ViewBag.Title = "ConsultarProduto";
}

<h2>ConsultarProduto</h2>

<p>
    @Html.ActionLink("Create New", "CadastrarProduto")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qtd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Desc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qtd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.ActionLink("Alterar", "AlterarProdutos", new { id=item.Id }) |
           
            @Html.ActionLink("Deletar", "DeletarProduto", new { id=item.Id })
        </td>
    </tr>
}

</table>

ElectroThunder/ElectroThunder/Views/ElectroThunder/Contatos.cshtml
@{
    ViewBag.Title = "Contatos";
}

<h2>Contatos</h2>
<script>

    function abreface()
    {
        location.href = "https://www.facebook.com/Electro-Thunder-2318528755038546/";
        }

        function abreins()
    {
        location.href = "https://www.instagram.com/electrothunder19/";
        }

</script>


<br />

<h1 class="txtcontados"> Como você pode falar com a gente;</h1>

<button class="button1" style="vertical-align:middle" onclick="abreface();"><span> Facebook</span></button>

<button class="button2" style="vertical-align:middle" onclick="abreins();"><span> Instagram</span></button>

<h1>Também pelo e-mail: electrothunder2019@gmail.com</h1>

ElectroThunder/ElectroThunder/Views/ElectroThunder/DeletarProduto.cshtml
@model ElectroThunder.Modelos.ProdutoModel

@{
    ViewBag.Title = "DeletarPruduto";
}

<h2>DeletarPruduto</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProdutoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qtd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qtd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volta para consulta", "ConsultarProduto")
        </div>
    }
</div>

ElectroThunder/ElectroThunder/Views/ElectroThunder/Inicio.cshtml
@{
    ViewBag.Title = "Electro Thunder";
}

<h2>Hello Boys, Hello Gils</h2>

ElectroThunder/ElectroThunder/Views/ElectroThunder/QuemSomos.cshtml
@{
    ViewBag.Title = "QuemSomos";
}

<h2>Quem Somos</h2>
<p class="QS">Quem somos?</p>
<p class="Sla">Somos uma empresa de eletrônicos</p>


<title class="">  Electro Thunder </title>

ElectroThunder/ElectroThunder/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ElectroThunder/ElectroThunder/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ElectroThunder/ElectroThunder/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ElectroThunder/ElectroThunder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Electro Thunder</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Inicio", "ElectroThunder", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sobre", "QuemSomos", "ElectroThunder")</li>
                    <li>@Html.ActionLink("Contato", "Contatos", "ElectroThunder")</li>
                    <li>@Html.ActionLink("Cadastrar Produto", "CadastrarProduto", "ElectroThunder")</li>
                    <li>@Html.ActionLink("Consutar Produto", "ConsultarProduto", "ElectroThunder")</li>


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Electro Thunder</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>